# Reference: https://build-cpp.github.io/cmkr/cmake-toml
[project]
name = "regenny"

[vcpkg]
version = "2022.05.10"
packages = [
    "imgui[docking-experimental,freetype,sdl2-binding,opengl3-binding]",
    "fmt",
    "pegtl",
    "nativefiledialog",
    "spdlog",
    "utfcpp",
    "nlohmann-json",
    "glad[gl-api-30]",
]

[fetch-content]
sdkgenny = { git = "https://github.com/cursey/sdkgenny.git", tag = "f60d156f7b9b4d11b8c91ea14b255edf0a1158c9" }

[find-package]
imgui = {}
fmt = {}
pegtl = {}
unofficial-nativefiledialog = {}
spdlog = {}
utf8cpp = {}
SDL2 = {}
nlohmann_json = {}
glad = {}

[conditions]
static = "${VCPKG_TARGET_TRIPLET} MATCHES \".+static\""

[target.regenny]
type = "executable"
sources = [
    "src/**.cpp",
    "src/**.hpp",
    "thirdparty/**.cpp",
    "thirdparty/**.hpp",
    "thirdparty/**.h",
]
windows.sources = ["src/**.rc"]
include-directories = [
    "src/",
    "thirdparty/scope_gaurd/",
    "thirdparty/SDL_Trigger/",
]
link-libraries = [
    "imgui::imgui",
    "fmt::fmt",
    "taocpp::pegtl",
    "unofficial::nativefiledialog::nfd",
    "spdlog::spdlog",
    "utf8cpp",
    "SDL2::SDL2",
    "SDL2::SDL2main",
    "nlohmann_json::nlohmann_json",
    "glad::glad",
    "sdkgenny::sdkgenny",
]
compile-definitions = ["UTF_CPP_CPLUSPLUS=201103L"]
compile-features = ["cxx_std_17"]

[target.regenny.properties]
static.MSVC_RUNTIME_LIBRARY = "MultiThreaded$<$<CONFIG:Debug>:Debug>"

[target.test0]
type = "executable"
sources = ["examples/test0.cpp"]
compile-features = ["cxx_std_17"]

[[install]]
targets = ["regenny"]
destination = "bin"
